import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader, Badge, Field, PrimaryButton, Screen, SecondaryButton } from '@/components/ui';
import { useAuth } from '@/contexts/auth-context';
import { Board, KanbanRepository, Task } from '@/infrastructure/kanban/kanban.repository';
import { theme } from '@/theme';

const repository = new KanbanRepository();
const dayLabels = ['L', 'M', 'X', 'J', 'V', 'S', 'D'];

export default function KanbanScreen() {
  const router = useRouter(); const { logout } = useAuth();
  const [boards, setBoards] = useState<Board[]>([]); const [selected, setSelected] = useState<Board | null>(null); const [loading, setLoading] = useState(true); const [modal, setModal] = useState<'board' | 'task' | null>(null); const [error, setError] = useState('');
  const [boardName, setBoardName] = useState(''); const [taskTitle, setTaskTitle] = useState(''); const [taskPoints, setTaskPoints] = useState(''); const [taskMinutes, setTaskMinutes] = useState(''); const [taskDate, setTaskDate] = useState(''); const [taskTime, setTaskTime] = useState(''); const [recurrence, setRecurrence] = useState<number[]>([]);

  const loadBoards = async () => { setLoading(true); try { const result = await repository.listBoards(); const next = result.boards ?? []; setBoards(next); if (!selected && next[0]) setSelected(next[0]); else if (selected) setSelected(await repository.getBoard(selected.id)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar el Kanban'); } finally { setLoading(false); } };
  useEffect(() => { loadBoards(); }, []);
  const createBoard = async () => { if (!boardName.trim()) return; try { const board = await repository.createBoard({ name: boardName.trim() }); setBoardName(''); setModal(null); setSelected(board); await loadBoards(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo crear la pizarra'); } };
  const createTask = async () => { if (!selected || !taskTitle.trim() || !selected.columns[0]) return; try { await repository.createTask(selected.id, { title: taskTitle.trim(), columnId: selected.columns[0].id, priority: 'medium', effortPoints: taskPoints ? Number(taskPoints) : undefined, estimatedMinutes: taskMinutes ? Number(taskMinutes) : undefined, dueDate: taskDate || undefined, dueTime: taskTime || undefined, recurrence: recurrence.length ? { type: 'weekly', days: recurrence } : undefined }); setModal(null); setTaskTitle(''); setTaskPoints(''); setTaskMinutes(''); setTaskDate(''); setTaskTime(''); setRecurrence([]); await loadBoards(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo crear la tarea'); } };
  const moveTask = async (task: Task, index: number) => { if (!selected || !selected.columns[index]) return; try { await repository.moveTask(task.id, selected.columns[index].id); setSelected(await repository.getBoard(selected.id)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo mover la tarea'); } };
  const selectedColumnCount = selected?.columns.length ?? 0;

  return <Screen><AppHeader title="Kanban" subtitle="Organiza el trabajo sin perder de vista el día." right={<View style={styles.headerActions}><SecondaryButton title="← Calendario" onPress={() => router.push('/calendar')} /><SecondaryButton title="Salir" onPress={() => logout().then(() => router.replace('/login'))}/></View>}/>
    <View style={styles.toolbar}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.boardTabs}>{boards.map((board) => <Pressable key={board.id} onPress={() => repository.getBoard(board.id).then(setSelected)} style={[styles.boardTab, selected?.id === board.id && styles.boardTabActive]}><Text style={styles.boardTabText}>{board.name}</Text></Pressable>)}<SecondaryButton title="+ Pizarra" onPress={() => setModal('board')}/><PrimaryButton title="+ Tarea" onPress={() => setModal('task')} disabled={!selected}/></ScrollView></View>
    {loading && !selected ? <ActivityIndicator color={theme.colors.ink} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.columns}>{(selected?.columns ?? []).sort((a,b) => a.position-b.position).map((column, index) => <View key={column.id} style={styles.column}><View style={styles.columnHead}><View style={[styles.dot,{backgroundColor:column.color || theme.colors.ink}]} /><Text style={styles.columnTitle}>{column.name}</Text><Text style={styles.count}>{(selected?.tasks ?? []).filter(t => t.columnId === column.id).length}</Text></View>{(selected?.tasks ?? []).filter(t => t.columnId === column.id && !t.archivedAt).map((task) => <Pressable key={task.id} onPress={() => index < selectedColumnCount - 1 && moveTask(task,index+1)} style={styles.card}><Text style={styles.taskTitle}>{task.title}</Text><View style={styles.meta}>{task.priority ? <Badge label={task.priority} /> : null}{task.assignee ? <Text style={styles.metaText}>👤 {task.assignee.username}</Text> : <Text style={styles.metaText}>👤 Sin asignar</Text>}</View><View style={styles.tags}>{(task.tags ?? []).map((tag) => <Badge key={tag} label={tag}/>)}</View><Text style={styles.metaText}>{task.effortPoints ? `⭐ ${task.effortPoints}` : ''}{task.estimatedMinutes ? `  ⏱ ${task.estimatedMinutes}m` : ''}{task.recurrence ? `  ↻ ${task.recurrence.days.map((d) => dayLabels[d-1]).join(' · ')}` : ''}</Text><View style={[styles.status,{backgroundColor:column.color || theme.colors.ink}]}><Text style={styles.statusText}>{column.name}</Text></View></Pressable>)}</View>)}</ScrollView>
    <Text style={styles.hint}>Pulsa una tarjeta para avanzar al siguiente estado.</Text>
    <Modal visible={modal === 'board'} transparent animationType="fade" onRequestClose={() => setModal(null)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>Nueva pizarra</Text><Field label="Nombre" value={boardName} onChangeText={setBoardName}/><PrimaryButton title="Crear" onPress={createBoard}/><SecondaryButton title="Cancelar" onPress={() => setModal(null)}/></View></View></Modal>
    <Modal visible={modal === 'task'} transparent animationType="slide" onRequestClose={() => setModal(null)}><View style={styles.overlay}><ScrollView style={styles.modal}><Text style={styles.modalTitle}>Nueva tarea</Text><Field label="Título" value={taskTitle} onChangeText={setTaskTitle}/><Field label="Puntos de esfuerzo" value={taskPoints} onChangeText={setTaskPoints} keyboardType="numeric"/><Field label="Minutos estimados" value={taskMinutes} onChangeText={setTaskMinutes} keyboardType="numeric"/><Field label="Fecha opcional (YYYY-MM-DD)" value={taskDate} onChangeText={setTaskDate}/><Field label="Hora opcional (HH:mm)" value={taskTime} onChangeText={setTaskTime}/><Text style={styles.label}>Frecuencia semanal opcional</Text><View style={styles.weekdays}>{dayLabels.map((label,i) => <Pressable key={label} onPress={() => setRecurrence((days) => days.includes(i+1) ? days.filter((d) => d !== i+1) : [...days,i+1])} style={[styles.weekday, recurrence.includes(i+1) && styles.weekdayActive]}><Text style={recurrence.includes(i+1) ? styles.weekdayActiveText : styles.weekdayText}>{label}</Text></Pressable>)}</View><PrimaryButton title="Crear tarea" onPress={createTask}/><SecondaryButton title="Cancelar" onPress={() => setModal(null)}/></ScrollView></View></Modal>
  </Screen>;
}

const styles=StyleSheet.create({headerActions:{flexDirection:'row',gap:8},toolbar:{marginBottom:theme.spacing.lg},boardTabs:{gap:8,alignItems:'center'},boardTab:{paddingHorizontal:14,paddingVertical:9,borderWidth:1,borderColor:theme.colors.inkFaint,borderRadius:7},boardTabActive:{backgroundColor:theme.colors.ink},boardTabText:{color:theme.colors.ink},columns:{gap:16,paddingBottom:40},column:{width:280,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.inkFaint,borderRadius:12,padding:12,minHeight:180},columnHead:{flexDirection:'row',alignItems:'center',gap:8,paddingBottom:12},dot:{width:10,height:10,borderRadius:5},columnTitle:{fontWeight:'600',color:theme.colors.ink,flex:1},count:{color:theme.colors.inkMid,fontSize:12},card:{backgroundColor:theme.colors.white,borderWidth:1,borderColor:theme.colors.inkFaint,borderRadius:10,padding:13,marginBottom:10,position:'relative'},taskTitle:{fontWeight:'600',color:theme.colors.ink,paddingRight:50,marginBottom:8},meta:{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'},metaText:{fontSize:11,color:theme.colors.inkMid},tags:{flexDirection:'row',gap:4,flexWrap:'wrap',marginVertical:7},status:{position:'absolute',right:10,top:10,borderRadius:999,paddingHorizontal:7,paddingVertical:3},statusText:{color:'#fff',fontSize:9},hint:{color:theme.colors.inkMid,textAlign:'center',fontSize:11,marginVertical:10},error:{color:theme.colors.error,marginBottom:10},overlay:{flex:1,backgroundColor:'rgba(26,24,20,.4)',justifyContent:'center',padding:20},modal:{backgroundColor:theme.colors.background,borderRadius:14,padding:24,gap:14,maxHeight:'90%'},modalTitle:{fontFamily:'serif',fontSize:28,color:theme.colors.ink},label:{color:theme.colors.inkMid,fontSize:13},weekdays:{flexDirection:'row',gap:6},weekday:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:theme.colors.inkFaint,alignItems:'center',justifyContent:'center',backgroundColor:theme.colors.white},weekdayActive:{backgroundColor:theme.colors.ink},weekdayText:{color:theme.colors.ink},weekdayActiveText:{color:'#fff'}});
